export const browserCoreExamples = [
  "starforge browser status",
  "starforge browser start",
  "starforge browser stop",
  "starforge browser tabs",
  "starforge browser open https://example.com",
  "starforge browser focus abcd1234",
  "starforge browser close abcd1234",
  "starforge browser screenshot",
  "starforge browser screenshot --full-page",
  "starforge browser screenshot --ref 12",
  "starforge browser snapshot",
  "starforge browser snapshot --format aria --limit 200",
  "starforge browser snapshot --efficient",
  "starforge browser snapshot --labels",
];

export const browserActionExamples = [
  "starforge browser navigate https://example.com",
  "starforge browser resize 1280 720",
  "starforge browser click 12 --double",
  'starforge browser type 23 "hello" --submit',
  "starforge browser press Enter",
  "starforge browser hover 44",
  "starforge browser drag 10 11",
  "starforge browser select 9 OptionA OptionB",
  "starforge browser upload /tmp/file.pdf",
  'starforge browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "starforge browser dialog --accept",
  'starforge browser wait --text "Done"',
  "starforge browser evaluate --fn '(el) => el.textContent' --ref 7",
  "starforge browser console --level error",
  "starforge browser pdf",
];
